apiVersion: v2
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
# giantswarm app version
version: CHART_VERSION_PLACEHOLDER
name: csi-external-snapshotter-app
description: CSI external snapshotter which deploys CRDs and controllers
home: https://github.com/giantswarm/csi-external-snapshotter-app
icon: https://s.giantswarm.io/app-icons/csi/1/dark.svg
annotations:
  application.giantswarm.io/team: rocket
  io.giantswarm.application.upstream-chart-url: "https://github.com/kubernetes-csi/external-snapshotter"
  io.giantswarm.application.upstream-chart-version: "APP_VERSION_PLACEHOLDER"
dependencies:
  - name: csi-external-snapshotter-crds
    version: CRD_VERSION_PLACEHOLDER
    condition: crds.install
sources:
  - https://github.com/giantswarm/csi-external-snapshotter-app
  - https://github.com/kubernetes-csi/external-snapshotter
