apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapshot-webhook
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - snapshot-validation-service.{{ .Release.Namespace }}.svc.cluster.local
  - snapshot-validation-service.{{ .Release.Namespace }}.svc
  issuerRef:
    name: snapshot-webhook-issuer
  secretName: snapshot-validation-secret
