apiVersion: v1
kind: Service
metadata:
  name: snapshot-validation-service
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: snapshot-validation
