{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: snapshot-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snapshot-controller
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    {{- toYaml .Values.verticalPodAutoscaler.snapshotController.containerPolicies | nindent 4 }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: snapshot-validation-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snapshot-validation-deployment
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    {{- toYaml .Values.verticalPodAutoscaler.validationWebhook.containerPolicies | nindent 4 }}
{{- end }}
