# https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/webhook-example/webhook.yaml
{{- if .Values.validationWebhook.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-validation-deployment
  labels:
    app: snapshot-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-validation
  template:
    metadata:
      labels:
        app: snapshot-validation
    spec:
      containers:
      - name: snapshot-validation
        image: "{{ .Values.validationWebhook.image }}:{{ .Values.validationWebhook.tag }}"
        imagePullPolicy: IfNotPresent
        args:
        - "--tls-cert-file=/etc/snapshot-validation-webhook/certs/tls.crt"
        - "--tls-private-key-file=/etc/snapshot-validation-webhook/certs/tls.key"
        - "--v=5"
        ports:
        - containerPort: 443
        volumeMounts:
          - name: snapshot-validation-webhook-certs
            mountPath: /etc/snapshot-validation-webhook/certs
            readOnly: true
      volumes:
        - name: snapshot-validation-webhook-certs
          secret:
            secretName: snapshot-validation-secret
---
apiVersion: v1
kind: Service
metadata:
  name: snapshot-validation-service
spec:
  selector:
    app: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
{{- end }}