{{/*
Generated by sync/patches/crds/patch.sh -- do not edit.

Names of the CRDs shipped by the csi-external-snapshotter-crds dependency chart. The
crd-adopt hook iterates over these to hand ownership to Helm.
*/}}
{{- define "crdNames" -}}
volumegroupsnapshotclasses.groupsnapshot.storage.k8s.io volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io volumegroupsnapshots.groupsnapshot.storage.k8s.io volumesnapshotclasses.snapshot.storage.k8s.io volumesnapshotcontents.snapshot.storage.k8s.io volumesnapshots.snapshot.storage.k8s.io
{{- end -}}
