version: 2.1
orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "push-to-default-app-catalog"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "csi-external-snapshotter-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
