apiVersion: v2
# upstream version
appVersion: v8.6.0
# giantswarm app version
version: 0.4.0
name: csi-external-snapshotter-app
description: CSI external snapshotter which deploys CRDs and controllers
home: https://github.com/giantswarm/csi-external-snapshotter-app
icon: https://s.giantswarm.io/app-icons/csi/1/dark.svg
annotations:
  application.giantswarm.io/team: rocket
  io.giantswarm.application.upstream-chart-url: "https://github.com/kubernetes-csi/external-snapshotter"
  io.giantswarm.application.upstream-chart-version: "v8.6.0"
dependencies:
  - name: csi-external-snapshotter-crds
    version: 8.6.0
    condition: crds.install
sources:
  - https://github.com/giantswarm/csi-external-snapshotter-app
  - https://github.com/kubernetes-csi/external-snapshotter
