crds:
  install: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

dockerKubectl:
  image: quay.io/giantswarm/docker-kubectl
  tag: "1.23.6"

snapshotController:
  image: registry.k8s.io/sig-storage/snapshot-controller
  tag: v5.0.1

validationWebhook:
  image: registry.k8s.io/sig-storage/snapshot-validation-webhook
  tag: v5.0.1

defaults:
  volumesnapshotclass:
    create: false
    name: ""
    driver: ""
