crds:
  install: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

dockerKubectl:
  image: quay.io/giantswarm/docker-kubectl
  tag: "1.33.4"

snapshotController:
  image: registry.k8s.io/sig-storage/snapshot-controller
  tag: v8.6.0
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "256Mi"
      cpu: "200m"

defaults:
  volumesnapshotclass:
    create: false
    name: ""
    driver: ""
