{{- if eq (include "crdAdoptEnabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crdAdopt" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "crdAdoptAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crdAdopt" . | quote }}
    {{- include "labels.common" . | nindent 4 }}
    role: {{ include "crdAdoptSelector" . | quote }}
{{- end }}
