#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ; readonly SCRIPT_DIR
source "${SCRIPT_DIR}"/../../_helpers.sh

echo "Updating the ${CRD_CHART_NAME} dependency chart"

cd "${REPO_DIR}"

# The version currently published for the CRD chart. Read before the manifest
# overwrites Chart.yaml, so that a sync which does not touch the CRDs leaves the
# dependency version alone.
CURRENT_CRD_CHART_VERSION=$(yq -r '.version // "0.0.0"' "${CRD_CHART_DIR}/Chart.yaml" 2>/dev/null || echo "0.0.0")
case "${CURRENT_CRD_CHART_VERSION}" in
	"" | "null") CURRENT_CRD_CHART_VERSION="0.0.0" ;;
esac

mkdir -p "${CRD_CHART_DIR}/templates"
cp -R "${SCRIPT_DIR}/manifests/." "${CHART_DIR}/"

# Replace, rather than merge, so a CRD that upstream drops disappears from the
# chart too.
find "${CRD_CHART_DIR}/templates" -type f -delete

# The CRDs go in as ordinary templates, not into a `crds/` directory: Helm never
# upgrades or deletes the contents of `crds/`, which is exactly the problem this
# chart used to work around with a `kubectl apply` job.
for crd in "${VENDIR_SYNC_DIR}"/client/config/crd/*.yaml; do
	[ "$(basename "${crd}")" = "kustomization.yaml" ] && continue
	cp "${crd}" "${CRD_CHART_DIR}/templates/"
done

# Keep the CRDs on `helm uninstall` -- deleting them would take every
# VolumeSnapshot in the cluster with them. Merged into the existing annotations
# (upstream already sets controller-gen and api-approved ones).
for crd in "${CRD_CHART_DIR}"/templates/*.yaml; do
	yq eval '.metadata.annotations = (.metadata.annotations // {}) | .metadata.annotations += {"helm.sh/resource-policy": "keep"}' -i "${crd}"
done

# Generate the CRD name list consumed by the crd-adopt hook, so that adding or
# removing a CRD upstream does not need a hand edit of the job.
# one yq invocation per file: passing several at once makes yq emit `---`
# document separators into the output.
CRD_NAMES=""
for crd in $(ls "${CRD_CHART_DIR}"/templates/*.yaml | sort); do
	CRD_NAMES="${CRD_NAMES:+${CRD_NAMES} }$(yq -r '.metadata.name' "${crd}")"
done
cat >"${CHART_DIR}/templates/crd-adopt/_crd-names.tpl" <<EOF
{{/*
Generated by sync/patches/crds/patch.sh -- do not edit.

Names of the CRDs shipped by the ${CRD_CHART_NAME} dependency chart. The
crd-adopt hook iterates over these to hand ownership to Helm.
*/}}
{{- define "crdNames" -}}
${CRD_NAMES}
{{- end -}}
EOF

# Bump the CRD chart version only when the CRDs actually changed, so a
# controller-only upstream release does not churn the dependency version.
CRDS_CHANGED=0
if ! git diff --quiet HEAD -- "${CRD_CHART_DIR}/templates/"; then
	CRDS_CHANGED=1
fi
if git ls-files --others --exclude-standard -- "${CRD_CHART_DIR}/templates/" | grep -q .; then
	CRDS_CHANGED=1
fi

if [[ ${CRDS_CHANGED} -eq 1 ]]; then
	CRD_CHART_VERSION="${UPSTREAM_VERSION#v}"
else
	CRD_CHART_VERSION="${CURRENT_CRD_CHART_VERSION}"
fi

sedi "s|CRD_CHART_VERSION_PLACEHOLDER|${CRD_CHART_VERSION}|" "${CRD_CHART_DIR}/Chart.yaml"
sedi "s|CRD_VERSION_PLACEHOLDER|${CRD_CHART_VERSION}|" "${CHART_DIR}/Chart.yaml"
